name: PENet
dependencies:
  - python=3.7.4
  - pytorch=1.3.1
  - torchvision=0.4.2
  - cudatoolkit=10.0.130
  - numpy
  - matplotlib
  - Pillow
  - scikit-image
  - opencv
  - pip
  - pip:
    - opencv-contrib-python==3.4.2.17
